spring.application.name=SpringjwtDemo


server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
spring.datasource.username=root
spring.datasource.password=Shivam@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret = 11e7678dfe8bd7e2fced6952777695996e82054a72b263c96c72cb7be7fe0f22
app.jwt.expiration-ms = 3600000


razorpay.key-id=rzp_test_ShIuuLsjOORlLM
razorpay.key-secret=UiZYMrcBLkXVMGAa7TXpWxPy
razorpay.currency=INR
